# Generated by Django 4.2.13 on 2024-10-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kelas',
            table='kelas',
        ),
    ]
