# Generated by Django 4.2.13 on 2024-10-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_kelas_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nisn', models.IntegerField(max_length=10)),
                ('kelasId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kelas')),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True, max_length=50)),
                ('wktdatang', models.CharField(max_length=10)),
                ('wktpulang', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('HADIR', 'HADIR'), ('IZIN', 'IZIN'), ('SAKIT', 'SAKIT'), ('TELAT', 'TELAT'), ('PULANG', 'PULANG')], max_length=10)),
                ('siswaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.IntegerField(max_length=25)),
                ('kelasId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kelas')),
            ],
            options={
                'db_table': 'guru',
            },
        ),
    ]
