# Generated by Django 4.2.13 on 2024-10-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_siswa_kehadiran_guru'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kehadiran',
            table='kehadiran',
        ),
    ]
