# Generated by Django 4.2.13 on 2024-10-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_kelasid_guru_kelas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guru')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.siswa')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
