# Generated by Django 4.2.13 on 2024-10-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guru_nip_alter_siswa_nisn_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=10),
        ),
    ]
