# Generated by Django 4.2.13 on 2024-10-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_guru_nip_alter_siswa_nisn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.guru'),
        ),
        migrations.AlterField(
            model_name='user',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.siswa'),
        ),
    ]
