# Generated by Django 4.2.13 on 2024-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='wktdatang',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='wktpulang',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
