# Generated by Django 4.2.13 on 2024-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_kehadiran_wktdatang_alter_kehadiran_wktpulang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
