# Generated by Django 4.2.13 on 2024-10-14 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_guru_alter_user_siswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guru',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='api.guru'),
        ),
        migrations.AlterField(
            model_name='user',
            name='siswa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='api.siswa'),
        ),
    ]
