# Generated by Django 4.2.13 on 2024-10-14 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_guru_alter_user_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_profile', to='api.user'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siswa_profile', to='api.user'),
        ),
    ]
