# Generated by Django 4.2.13 on 2024-10-14 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_guru_user_siswa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.guru'),
        ),
        migrations.AlterField(
            model_name='user',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.siswa'),
        ),
    ]
