# Generated by Django 4.2.13 on 2024-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_kehadiran_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='keterangan',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='wktpulang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
