# Generated by Django 4.2.13 on 2024-10-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_kehadiran_keterangan_alter_kehadiran_wktpulang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.guru'),
        ),
        migrations.AlterField(
            model_name='user',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.siswa'),
        ),
    ]
